version: "3.8"

services:
  mysql:
    image: mysql:8
    container_name: mysql-container
    ports:
      - "3306:3306"
    env_file:
      - ./backend/.env
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network

  backend:
    build: ./backend
    container_name: healthconnect-backend
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    env_file:
      - ./backend/.env
    networks:
      - app-network

  frontend:
    build: ./frontend
    container_name: healthconnect-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - app-network

volumes:
  mysql_data:

networks:
  app-network:
    driver: bridge
